# Generated by Django 4.0.4 on 2022-05-17 10:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_category_cities_home_publisher_remove_student_person_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='home',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.category'),
        ),
    ]
